# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 638)
        MainWindow.setStyleSheet("font-style:Bebas Neue;\n"
"background:#000000;\n"
"color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stop_cracking_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_cracking_btn.setGeometry(QtCore.QRect(450, 430, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Oswald Medium")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stop_cracking_btn.setFont(font)
        self.stop_cracking_btn.setStyleSheet("background:#E6111B;\n"
"color:white;")
        self.stop_cracking_btn.setObjectName("stop_cracking_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 30, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.netflix_logo = QtWidgets.QFrame(self.centralwidget)
        self.netflix_logo.setGeometry(QtCore.QRect(20, -20, 191, 151))
        self.netflix_logo.setStyleSheet("image: url(:/Images/netflix__1_.png);")
        self.netflix_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.netflix_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.netflix_logo.setObjectName("netflix_logo")
        self.start_cracking_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_cracking_btn.setGeometry(QtCore.QRect(240, 430, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_cracking_btn.setFont(font)
        self.start_cracking_btn.setStyleSheet("background:#E6111B;\n"
"color:white;")
        self.start_cracking_btn.setObjectName("start_cracking_btn")
        self.animation_label = QtWidgets.QLabel(self.centralwidget)
        self.animation_label.setGeometry(QtCore.QRect(250, 110, 351, 281))
        self.animation_label.setStyleSheet("image:url(:/Images/0_KtkmC0AZuZrYAZD4.gif);")
        self.animation_label.setText("")
        self.animation_label.setObjectName("animation_label")
        self.guessing_psd_lbl = QtWidgets.QLabel(self.centralwidget)
        self.guessing_psd_lbl.setGeometry(QtCore.QRect(270, 530, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Oswald SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.guessing_psd_lbl.setFont(font)
        self.guessing_psd_lbl.setText("")
        self.guessing_psd_lbl.setObjectName("guessing_psd_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_cracking_btn.setText(_translate("MainWindow", "Stop Cracking"))
        self.label.setText(_translate("MainWindow", "Neflix Password Cracker"))
        self.start_cracking_btn.setText(_translate("MainWindow", "Start Cracking"))
import resources_rc
